version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: symfony/webpack-encore-bundle
    versions:
    - 1.11.0
    - 1.11.1
    - 1.11.2
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: sensio/framework-extra-bundle
    versions:
    - 6.0.0
    - 6.1.2
  - dependency-name: doctrine/orm
    versions:
    - 2.8.2
    - 2.8.3
    - 2.8.4
  - dependency-name: doctrine/doctrine-bundle
    versions:
    - 2.2.4
    - 2.3.0
    - 2.3.1
  - dependency-name: symfony/string
    versions:
    - 5.2.6
  - dependency-name: symfony/mailer
    versions:
    - 5.2.3
    - 5.2.6
  - dependency-name: symfony/mime
    versions:
    - 5.2.6
  - dependency-name: symfony/translation
    versions:
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/http-client
    versions:
    - 5.2.6
  - dependency-name: symfony/security-bundle
    versions:
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/web-profiler-bundle
    versions:
    - 5.2.4
    - 5.2.6
  - dependency-name: guzzlehttp/guzzle
    versions:
    - 7.3.0
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.29.0
    - 1.29.1
    - 1.30.0
    - 1.30.1
    - 1.30.2
  - dependency-name: symfony/messenger
    versions:
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/css-selector
    versions:
    - 5.2.4
  - dependency-name: symfony/cache
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/intl
    versions:
    - 5.2.4
  - dependency-name: symfony/process
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/debug-bundle
    versions:
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.3
    - 5.2.4
  - dependency-name: doctrine/annotations
    versions:
    - 1.12.1
  - dependency-name: symfony/flex
    versions:
    - 1.12.2
  - dependency-name: symfony/proxy-manager-bridge
    versions:
    - 5.2.3
  - dependency-name: symfony/property-access
    versions:
    - 5.2.3
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.3
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.3
