security:
    encoders:
        legacy:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000

        App\Domain\Entity\Account\Account:
            algorithm: sodium
            migrate_from:
                - legacy

    providers:
        app_user_provider:
            entity:
                class: App\Domain\Entity\Account\Account
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Infrastructure\Security\LaDanseFormAuthenticator
            logout:
                path: app_logout
                target: index
            lazy: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/secured,  roles: IS_AUTHENTICATED_REMEMBERED }
